### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by pathumego** [mooniak/stick-no-bills-font#74]
@paarandika URGENT

```
Merge complete!

[Note] 13:45:31 Building...

[Note] Generating the glyph class for combining marks...

Traceback (most recent call last):
  File "build.py", line 63, in <module>
    builder.build()
  File "/usr/local/lib/python2.7/dist-packages/hindkit-0.2.1-py2.7.egg/hindkit/builder.py", line 200, in build
    output_path = 'features/GENERATED_classes.fea'
  File "/usr/local/lib/python2.7/dist-packages/hindkit-0.2.1-py2.7.egg/hindkit/builder.py", line 424, in generate_glyph_classes
    glyph_names = [glyph.name for glyph in filter(filter_function, font)]
  File "/usr/local/lib/python2.7/dist-packages/robofab/objects/objectsBase.py", line 180, in __iter__
    yield self[name]
  File "/usr/local/lib/python2.7/dist-packages/robofab/objects/objectsBase.py", line 184, in __getitem__
    return self.layers.getDefaultLayer()[glyphName]
AttributeError: 'RFont' object has no 
```

**Comment by paarandika** [comment]
``` shell
cd ~/robofab
sudo git checkout master
sudo setup.py install
```

I will updated the provisioning script. If you want destroy the VM and provision again. But above will fix your current VM.
