### ISSUE TITLE
Build system errors

### ISSUE THREAD

**Issue by pathumego** [mooniak/stick-no-bills-font#89]
@paarandika I think this si something with welipilla.

it builds the files regardless of this.

```
Traceback (most recent call last):
  File "merger.py", line 11, in <module>
    from defcon import Font
  File "/usr/local/lib/python2.7/dist-packages/defcon/__init__.py", line 10, in <module>
    from defcon.objects.font import Font
  File "/usr/local/lib/python2.7/dist-packages/defcon/objects/font.py", line 8, in <module>
    from ufoLib import UFOReader, UFOWriter
ImportError: No module named ufoLib
Traceback (most recent call last):
  File "merger.py", line 11, in <module>
    from defcon import Font
  File "/usr/local/lib/python2.7/dist-packages/defcon/__init__.py", line 10, in <module>
    from defcon.objects.font import Font
  File "/usr/local/lib/python2.7/dist-packages/defcon/objects/font.py", line 8, in <module>
    from ufoLib import UFOReader, UFOWriter
ImportError: No module named ufoLib
Traceback (most recent call last):
  File "AFDKOPython/generate_designspace.py", line 4, in <module>
    from mutatorMath.ufo.document import DesignSpaceDocumentWriter
  File "/usr/local/lib/python2.7/dist-packages/mutatorMath/ufo/document.py", line 8, in <module>
    import defcon
  File "/usr/local/lib/python2.7/dist-packages/defcon/__init__.py", line 10, in <module>
    from defcon.objects.font import Font
  File "/usr/local/lib/python2.7/dist-packages/defcon/objects/font.py", line 8, in <module>
    from ufoLib import UFOReader, UFOWriter
ImportError: No module named ufoLib

```

**Comment by paarandika** [comment]
Destroy the vm and try  again

**Comment by pathumego** [comment]
I did still getting the error

**Comment by pathumego** [comment]
This error is stopping merging of new masters.The files ive been using for testing were built using the same old master, that is why there are shitloads of errors left.

**Comment by paarandika** [comment]
Should work now.
